descricao.obrigatorio=Descrição é obrigatória
name.obrigatorio=Nome é obrigatório
email.obrigatorio=Email é obrigatório
email.invalido=Email inválido
password.obrigatorio=Senha é obrigatória
active.obrigatorio=Ativo é obrigatório
wallet.obrigatorio=Carteira é obrigatória
category.obrigatorio=Categoria é obrigatória
title.obrigatorio=Título é obrigatório
amount.obrigatorio=Valor é obrigatório
amount.positivo=Valor deve ser maior que zero
transactionDate.obrigatorio=Data da transação é obrigatória
type.obrigatorio=Tipo é obrigatório
status.obrigatorio=Status é obrigatório
plan.obrigatorio=Plano é obrigatório
price.obrigatorio=Preço é obrigatório
user.obrigatorio=Usuário é obrigatório
token.obrigatorio=Token é obrigatório
